-- Create a table to store daily business metrics
-- This table is designed to be populated once a day (e.g., at midnight) to keep a historical record.
-- Supports tracking of active clients, churn, new signups, renewals, and operational capacity.

CREATE TABLE IF NOT EXISTS daily_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL DEFAULT CURRENT_DATE UNIQUE,
  
  -- Client Status Snapshots
  total_active_clients INTEGER DEFAULT 0,
  total_active_high_ticket INTEGER DEFAULT 0, -- NEW: Track premium clients separately
  total_paused_clients INTEGER DEFAULT 0,
  
  -- Daily Movements (Flow)
  new_signups INTEGER DEFAULT 0,         -- Altas del día (Brand new sales)
  renewals INTEGER DEFAULT 0,            -- NEW: Clients moving to next phase (Retention wins)
  reactivations INTEGER DEFAULT 0,       -- NEW: Paused -> Active
  
  cancellations INTEGER DEFAULT 0,       -- Bajas del día (Inactive)
  pauses_started INTEGER DEFAULT 0,      -- Pausas del día
  dropouts INTEGER DEFAULT 0,            -- Abandonos del día
  
  -- Coach & Operations
  active_clients_by_coach JSONB DEFAULT '{}'::jsonb, -- e.g. {"coach_id": 15}
  checkins_received INTEGER DEFAULT 0,   -- Forms submitted by clients today
  checkins_reviewed INTEGER DEFAULT 0,   -- Reviews completed by coaches today
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast date-range querying
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date ON daily_metrics(date);

-- Comment on table
COMMENT ON TABLE daily_metrics IS 'Historical daily snapshots of key business KPIs (Active clients, churn, revenue indicators, etc.)';

-- Function to calculate and insert/update the metrics for the current day
-- This function can be called manually or scheduled via pg_cron or an Edge Function.
CREATE OR REPLACE FUNCTION snapshot_daily_metrics()
RETURNS void AS $$
DECLARE
    today_date DATE := CURRENT_DATE;
    
    -- Variables for metrics
    v_total_active INTEGER;
    v_total_active_high_ticket INTEGER;
    v_total_paused INTEGER;
    
    v_new_signups INTEGER;
    v_renewals INTEGER;
    v_reactivations INTEGER;
    
    v_cancellations INTEGER;
    v_pauses_started INTEGER;
    v_dropouts INTEGER;
    
    v_checkins_received INTEGER;
    v_checkins_reviewed INTEGER;
    v_coach_metrics JSONB;
BEGIN
    -- 1. Snapshot of Total Counts (State)
    SELECT COUNT(*) INTO v_total_active
    FROM clients
    WHERE status = 'active';
    
    SELECT COUNT(*) INTO v_total_active_high_ticket
    FROM clients
    WHERE status = 'active' AND high_ticket = TRUE;

    SELECT COUNT(*) INTO v_total_paused
    FROM clients
    WHERE status = 'paused';

    -- 2. Daily Movements (Events happening 'today')
    
    -- New Signups (Created today OR start_date is today)
    -- We use Created Today as proxy for "Sale Made"
    SELECT COUNT(*) INTO v_new_signups
    FROM clients
    WHERE DATE(created_at) = today_date;

    -- Renewals (Clients who advanced phase today)
    -- Logic: Count clients whose current contract start date is today BUT are not new users (created_at < today)
    -- This assumes 'start_date' updates when a Renewal happens.
    -- OR we check specific phase renewal dates if they match today.
    -- Simplified approach: Check if start_date is today AND created_at was earlier.
    SELECT COUNT(*) INTO v_renewals
    FROM clients
    WHERE status = 'active'
      AND "start_date"::DATE = today_date
      AND DATE(created_at) < today_date;

    -- Cancellations (Inactive status + inactiveDate is today)
    SELECT COUNT(*) INTO v_cancellations
    FROM clients
    WHERE status = 'inactive' 
      AND "inactiveDate"::DATE = today_date;

    -- Pauses (Paused status + pauseDate is today)
    SELECT COUNT(*) INTO v_pauses_started
    FROM clients
    WHERE status = 'paused' 
      AND "pauseDate"::DATE = today_date;
      
    -- Dropouts (Dropout status + abandonmentDate is today)
    SELECT COUNT(*) INTO v_dropouts
    FROM clients
    WHERE status = 'dropout' 
      AND "abandonmentDate"::DATE = today_date;
      
    -- Reactivations (Active status, but were paused recently? Hard to track without logs.
    -- Alternative: Start date is today? No, start date implies contract start.
    -- If we don't have a 'reactivationDate', we might skip or assume Start Date = Today creates a renewal/reactivation overlap.
    -- For now, we will leave Reactivations as 0 unless we add a specific field to Client for 'last_reactivation_date'.
    v_reactivations := 0;


    -- 3. Operational Metrics
    -- Active clients per coach
    SELECT COALESCE(jsonb_object_agg(coach_id, count), '{}'::jsonb) INTO v_coach_metrics
    FROM (
        SELECT coach_id, COUNT(*) as count
        FROM clients
        WHERE status = 'active'
        GROUP BY coach_id
    ) sub;

    -- Check-ins received today
    SELECT COUNT(*) INTO v_checkins_received
    FROM checkins
    WHERE DATE(created_at) = today_date;
    
    -- Check-ins reviewed today
    SELECT COUNT(*) INTO v_checkins_reviewed
    FROM checkins
    WHERE status = 'reviewed' AND DATE(updated_at) = today_date;

    -- 4. Upsert into daily_metrics
    INSERT INTO daily_metrics (
        date,
        total_active_clients,
        total_active_high_ticket,
        total_paused_clients,
        new_signups,
        renewals,
        reactivations,
        cancellations,
        pauses_started,
        dropouts,
        active_clients_by_coach,
        checkins_received,
        checkins_reviewed
    ) VALUES (
        today_date,
        v_total_active,
        v_total_active_high_ticket,
        v_total_paused,
        v_new_signups,
        v_renewals,
        v_reactivations,
        v_cancellations,
        v_pauses_started,
        v_dropouts,
        v_coach_metrics,
        v_checkins_received,
        v_checkins_reviewed
    )
    ON CONFLICT (date) DO UPDATE SET
        total_active_clients = EXCLUDED.total_active_clients,
        total_active_high_ticket = EXCLUDED.total_active_high_ticket,
        total_paused_clients = EXCLUDED.total_paused_clients,
        new_signups = EXCLUDED.new_signups,
        renewals = EXCLUDED.renewals,
        reactivations = EXCLUDED.reactivations,
        cancellations = EXCLUDED.cancellations,
        pauses_started = EXCLUDED.pauses_started,
        dropouts = EXCLUDED.dropouts,
        active_clients_by_coach = EXCLUDED.active_clients_by_coach,
        checkins_received = EXCLUDED.checkins_received,
        checkins_reviewed = EXCLUDED.checkins_reviewed,
        created_at = NOW(); -- Touch timestamp

END;
$$ LANGUAGE plpgsql;
