-- =====================================================
-- FIX: Actualizar snapshot_daily_metrics para usar clientes_pt_notion
-- =====================================================
-- PROBLEMA: La función original usaba la tabla "clients" que no existe
-- SOLUCIÓN: Usar "clientes_pt_notion" con los nombres de campos correctos

-- Primero, crear la tabla si no existe
CREATE TABLE IF NOT EXISTS daily_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL DEFAULT CURRENT_DATE UNIQUE,

  -- Client Status Snapshots
  total_active_clients INTEGER DEFAULT 0,
  total_active_high_ticket INTEGER DEFAULT 0,
  total_paused_clients INTEGER DEFAULT 0,
  total_inactive_clients INTEGER DEFAULT 0,
  total_dropout_clients INTEGER DEFAULT 0,

  -- Daily Movements (Flow)
  new_signups INTEGER DEFAULT 0,
  renewals INTEGER DEFAULT 0,
  reactivations INTEGER DEFAULT 0,
  cancellations INTEGER DEFAULT 0,
  pauses_started INTEGER DEFAULT 0,
  dropouts INTEGER DEFAULT 0,

  -- Coach & Operations
  active_clients_by_coach JSONB DEFAULT '{}'::jsonb,
  checkins_received INTEGER DEFAULT 0,
  checkins_reviewed INTEGER DEFAULT 0,

  -- Testimonials
  testimonials_count INTEGER DEFAULT 0,

  -- Sales (from sales table)
  sales_count INTEGER DEFAULT 0,
  sales_amount NUMERIC(12,2) DEFAULT 0,
  renewals_amount NUMERIC(12,2) DEFAULT 0,

  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Añadir columnas si no existen
ALTER TABLE daily_metrics ADD COLUMN IF NOT EXISTS total_inactive_clients INTEGER DEFAULT 0;
ALTER TABLE daily_metrics ADD COLUMN IF NOT EXISTS total_dropout_clients INTEGER DEFAULT 0;
ALTER TABLE daily_metrics ADD COLUMN IF NOT EXISTS testimonials_count INTEGER DEFAULT 0;
ALTER TABLE daily_metrics ADD COLUMN IF NOT EXISTS sales_count INTEGER DEFAULT 0;
ALTER TABLE daily_metrics ADD COLUMN IF NOT EXISTS sales_amount NUMERIC(12,2) DEFAULT 0;
ALTER TABLE daily_metrics ADD COLUMN IF NOT EXISTS renewals_amount NUMERIC(12,2) DEFAULT 0;

-- Index
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date ON daily_metrics(date);

-- =====================================================
-- FUNCIÓN CORREGIDA: Usa clientes_pt_notion
-- =====================================================
CREATE OR REPLACE FUNCTION snapshot_daily_metrics()
RETURNS void AS $$
DECLARE
    today_date DATE := CURRENT_DATE;

    -- Variables for metrics
    v_total_active INTEGER := 0;
    v_total_active_high_ticket INTEGER := 0;
    v_total_paused INTEGER := 0;
    v_total_inactive INTEGER := 0;
    v_total_dropout INTEGER := 0;

    v_new_signups INTEGER := 0;
    v_renewals INTEGER := 0;
    v_reactivations INTEGER := 0;

    v_cancellations INTEGER := 0;
    v_pauses_started INTEGER := 0;
    v_dropouts INTEGER := 0;

    v_checkins_received INTEGER := 0;
    v_checkins_reviewed INTEGER := 0;
    v_testimonials INTEGER := 0;

    v_sales_count INTEGER := 0;
    v_sales_amount NUMERIC(12,2) := 0;
    v_renewals_amount NUMERIC(12,2) := 0;

    v_coach_metrics JSONB;
BEGIN
    -- =========================================
    -- 1. SNAPSHOT DE TOTALES (Estado actual)
    -- =========================================

    -- Total clientes activos
    SELECT COUNT(*) INTO v_total_active
    FROM clientes_pt_notion
    WHERE status = 'active';

    -- Total clientes activos high ticket
    BEGIN
        SELECT COUNT(*) INTO v_total_active_high_ticket
        FROM clientes_pt_notion
        WHERE status = 'active'
          AND high_ticket = TRUE;
    EXCEPTION WHEN undefined_column THEN
        v_total_active_high_ticket := 0;
    END;

    -- Total pausados
    SELECT COUNT(*) INTO v_total_paused
    FROM clientes_pt_notion
    WHERE status = 'paused';

    -- Total inactivos (bajas)
    SELECT COUNT(*) INTO v_total_inactive
    FROM clientes_pt_notion
    WHERE status = 'inactive';

    -- Total abandonos
    SELECT COUNT(*) INTO v_total_dropout
    FROM clientes_pt_notion
    WHERE status = 'dropout';

    -- =========================================
    -- 2. MOVIMIENTOS DEL DÍA
    -- =========================================

    -- Altas del día (creados hoy)
    SELECT COUNT(*) INTO v_new_signups
    FROM clientes_pt_notion
    WHERE DATE(created_at) = today_date;

    -- Bajas del día (property_fecha_de_baja = hoy)
    SELECT COUNT(*) INTO v_cancellations
    FROM clientes_pt_notion
    WHERE (property_fecha_de_baja #>> '{}')::DATE = today_date;

    -- Pausas del día (property_fecha_pausa = hoy)
    SELECT COUNT(*) INTO v_pauses_started
    FROM clientes_pt_notion
    WHERE (property_fecha_pausa #>> '{}')::DATE = today_date;

    -- Abandonos del día (property_fecha_abandono = hoy)
    SELECT COUNT(*) INTO v_dropouts
    FROM clientes_pt_notion
    WHERE (property_fecha_abandono #>> '{}')::DATE = today_date;

    -- Renovaciones del día (verificadas hoy)
    SELECT COUNT(*) INTO v_renewals
    FROM clientes_pt_notion
    WHERE DATE(renewal_verified_at::DATE) = today_date;

    -- =========================================
    -- 3. MÉTRICAS POR COACH
    -- =========================================
    SELECT COALESCE(jsonb_object_agg(coach_name, client_count), '{}'::jsonb) INTO v_coach_metrics
    FROM (
        SELECT
            COALESCE(property_coach, 'Sin Asignar') as coach_name,
            COUNT(*) as client_count
        FROM clientes_pt_notion
        WHERE LOWER(COALESCE(status, property_estado_cliente, '')) SIMILAR TO '%(activo|active|alta|matriculado)%'
        GROUP BY COALESCE(property_coach, 'Sin Asignar')
    ) sub;

    -- =========================================
    -- 4. CHECK-INS
    -- =========================================
    -- Recibidos hoy
    BEGIN
        SELECT COUNT(*) INTO v_checkins_received
        FROM weekly_checkins
        WHERE DATE(created_at) = today_date;

        -- Revisados hoy
        SELECT COUNT(*) INTO v_checkins_reviewed
        FROM weekly_checkins
        WHERE status = 'reviewed' AND (DATE(updated_at) = today_date OR DATE(reviewed_at) = today_date);
    EXCEPTION WHEN undefined_table THEN
        v_checkins_received := 0;
        v_checkins_reviewed := 0;
    END;

    -- =========================================
    -- 5. TESTIMONIOS
    -- =========================================
    BEGIN
        SELECT COUNT(*) INTO v_testimonials
        FROM testimonials
        WHERE DATE(created_at) = today_date;
    EXCEPTION WHEN undefined_table THEN
        v_testimonials := 0;
    END;

    -- =========================================
    -- 6. VENTAS (si existe la tabla sales)
    -- =========================================
    BEGIN
        SELECT
            COUNT(*),
            COALESCE(SUM(sale_amount), 0)
        INTO v_sales_count, v_sales_amount
        FROM sales
        WHERE DATE(sale_date) = today_date
          AND transaction_type = 'sale';

        SELECT COALESCE(SUM(sale_amount), 0) INTO v_renewals_amount
        FROM sales
        WHERE DATE(sale_date) = today_date
          AND transaction_type = 'renewal';
    EXCEPTION WHEN undefined_table THEN
        v_sales_count := 0;
        v_sales_amount := 0;
        v_renewals_amount := 0;
    END;

    -- =========================================
    -- 7. UPSERT EN DAILY_METRICS
    -- =========================================
    INSERT INTO daily_metrics (
        date,
        total_active_clients,
        total_active_high_ticket,
        total_paused_clients,
        total_inactive_clients,
        total_dropout_clients,
        new_signups,
        renewals,
        reactivations,
        cancellations,
        pauses_started,
        dropouts,
        active_clients_by_coach,
        checkins_received,
        checkins_reviewed,
        testimonials_count,
        sales_count,
        sales_amount,
        renewals_amount
    ) VALUES (
        today_date,
        v_total_active,
        v_total_active_high_ticket,
        v_total_paused,
        v_total_inactive,
        v_total_dropout,
        v_new_signups,
        v_renewals,
        v_reactivations,
        v_cancellations,
        v_pauses_started,
        v_dropouts,
        v_coach_metrics,
        v_checkins_received,
        v_checkins_reviewed,
        v_testimonials,
        v_sales_count,
        v_sales_amount,
        v_renewals_amount
    )
    ON CONFLICT (date) DO UPDATE SET
        total_active_clients = EXCLUDED.total_active_clients,
        total_active_high_ticket = EXCLUDED.total_active_high_ticket,
        total_paused_clients = EXCLUDED.total_paused_clients,
        total_inactive_clients = EXCLUDED.total_inactive_clients,
        total_dropout_clients = EXCLUDED.total_dropout_clients,
        new_signups = EXCLUDED.new_signups,
        renewals = EXCLUDED.renewals,
        reactivations = EXCLUDED.reactivations,
        cancellations = EXCLUDED.cancellations,
        pauses_started = EXCLUDED.pauses_started,
        dropouts = EXCLUDED.dropouts,
        active_clients_by_coach = EXCLUDED.active_clients_by_coach,
        checkins_received = EXCLUDED.checkins_received,
        checkins_reviewed = EXCLUDED.checkins_reviewed,
        testimonials_count = EXCLUDED.testimonials_count,
        sales_count = EXCLUDED.sales_count,
        sales_amount = EXCLUDED.sales_amount,
        renewals_amount = EXCLUDED.renewals_amount,
        created_at = NOW();

    RAISE NOTICE 'Daily metrics snapshot completed for %', today_date;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- FUNCIÓN PARA GENERAR SNAPSHOT DE UN RANGO DE FECHAS
-- (útil para rellenar histórico)
-- =====================================================
CREATE OR REPLACE FUNCTION snapshot_daily_metrics_for_date(target_date DATE)
RETURNS void AS $$
DECLARE
    v_total_active INTEGER := 0;
    v_total_active_high_ticket INTEGER := 0;
    v_total_paused INTEGER := 0;
    v_total_inactive INTEGER := 0;
    v_total_dropout INTEGER := 0;

    v_new_signups INTEGER := 0;
    v_renewals INTEGER := 0;
    v_cancellations INTEGER := 0;
    v_pauses_started INTEGER := 0;
    v_dropouts INTEGER := 0;

    v_sales_count INTEGER := 0;
    v_sales_amount NUMERIC(12,2) := 0;
    v_renewals_amount NUMERIC(12,2) := 0;

    v_coach_metrics JSONB;
BEGIN
    -- Contar estados a esa fecha (aproximación basada en fechas de cambio)

    -- Activos: todos los que están activos Y (no tienen fecha_baja O su fecha_baja es posterior)
    SELECT COUNT(*) INTO v_total_active
    FROM clientes_pt_notion
    WHERE (
        LOWER(COALESCE(status, property_estado_cliente, '')) SIMILAR TO '%(activo|active|alta|matriculado)%'
        OR (
            DATE(created_at) <= target_date
            AND (property_fecha_de_baja IS NULL OR DATE(property_fecha_de_baja::DATE) > target_date)
            AND (property_fecha_abandono IS NULL OR DATE(property_fecha_abandono::DATE) > target_date)
            AND (property_fecha_pausa IS NULL OR DATE(property_fecha_pausa::DATE) > target_date)
        )
    );

    -- Altas de ese día
    SELECT COUNT(*) INTO v_new_signups
    FROM clientes_pt_notion
    WHERE DATE(created_at) = target_date;

    -- Bajas de ese día
    SELECT COUNT(*) INTO v_cancellations
    FROM clientes_pt_notion
    WHERE (property_fecha_de_baja #>> '{}')::DATE = target_date;

    -- Pausas de ese día
    SELECT COUNT(*) INTO v_pauses_started
    FROM clientes_pt_notion
    WHERE (property_fecha_pausa #>> '{}')::DATE = target_date;

    -- Abandonos de ese día
    SELECT COUNT(*) INTO v_dropouts
    FROM clientes_pt_notion
    WHERE (property_fecha_abandono #>> '{}')::DATE = target_date;

    -- Renovaciones de ese día
    SELECT COUNT(*) INTO v_renewals
    FROM clientes_pt_notion
    WHERE DATE(renewal_verified_at::DATE) = target_date;

    -- Coach metrics para esa fecha (aproximado)
    SELECT COALESCE(jsonb_object_agg(coach_name, client_count), '{}'::jsonb) INTO v_coach_metrics
    FROM (
        SELECT
            COALESCE(property_coach, 'Sin Asignar') as coach_name,
            COUNT(*) as client_count
        FROM clientes_pt_notion
        WHERE DATE(created_at) <= target_date
          AND (property_fecha_de_baja IS NULL OR DATE(property_fecha_de_baja::DATE) > target_date)
          AND (property_fecha_abandono IS NULL OR DATE(property_fecha_abandono::DATE) > target_date)
        GROUP BY COALESCE(property_coach, 'Sin Asignar')
    ) sub;

    -- Ventas de ese día
    BEGIN
        SELECT
            COUNT(*),
            COALESCE(SUM(sale_amount), 0)
        INTO v_sales_count, v_sales_amount
        FROM sales
        WHERE DATE(sale_date) = target_date
          AND transaction_type = 'sale';

        SELECT COALESCE(SUM(sale_amount), 0) INTO v_renewals_amount
        FROM sales
        WHERE DATE(sale_date) = target_date
          AND transaction_type = 'renewal';
    EXCEPTION WHEN undefined_table THEN
        v_sales_count := 0;
        v_sales_amount := 0;
        v_renewals_amount := 0;
    END;

    -- Upsert
    INSERT INTO daily_metrics (
        date,
        total_active_clients,
        new_signups,
        renewals,
        cancellations,
        pauses_started,
        dropouts,
        active_clients_by_coach,
        sales_count,
        sales_amount,
        renewals_amount
    ) VALUES (
        target_date,
        v_total_active,
        v_new_signups,
        v_renewals,
        v_cancellations,
        v_pauses_started,
        v_dropouts,
        v_coach_metrics,
        v_sales_count,
        v_sales_amount,
        v_renewals_amount
    )
    ON CONFLICT (date) DO UPDATE SET
        total_active_clients = EXCLUDED.total_active_clients,
        new_signups = EXCLUDED.new_signups,
        renewals = EXCLUDED.renewals,
        cancellations = EXCLUDED.cancellations,
        pauses_started = EXCLUDED.pauses_started,
        dropouts = EXCLUDED.dropouts,
        active_clients_by_coach = EXCLUDED.active_clients_by_coach,
        sales_count = EXCLUDED.sales_count,
        sales_amount = EXCLUDED.sales_amount,
        renewals_amount = EXCLUDED.renewals_amount,
        created_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- EJECUTAR SNAPSHOT PARA HOY
-- =====================================================
SELECT snapshot_daily_metrics();

-- =====================================================
-- OPCIONAL: Rellenar últimos 30 días de histórico
-- =====================================================
-- DO $$
-- DECLARE
--     d DATE;
-- BEGIN
--     FOR d IN SELECT generate_series(CURRENT_DATE - 30, CURRENT_DATE, '1 day'::interval)::date
--     LOOP
--         PERFORM snapshot_daily_metrics_for_date(d);
--     END LOOP;
-- END $$;

COMMENT ON FUNCTION snapshot_daily_metrics() IS 'Genera snapshot diario de métricas usando clientes_pt_notion. Ejecutar diariamente vía cron o Edge Function.';
